// Curated landmark backdrops, all from Wikimedia Commons.
// Every URL was verified to serve `Access-Control-Allow-Origin: *`, which is what
// lets us read the pixels into a canvas and still export the result.
// Add your own: any 1920px-wide upload.wikimedia.org thumb URL works.
// `the: true` means the name needs a leading "the" inside a sentence, as in
// "at the Colosseum". Leave it off for names that stand alone ("at Stonehenge").
export const LANDMARKS = [
  {
    name: 'Eiffel Tower',
    the: true,
    place: 'Paris, France',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Paris_-_The_Eiffel_Tower_in_spring_-_2307.jpg/1920px-Paris_-_The_Eiffel_Tower_in_spring_-_2307.jpg',
    credit: 'Jorge Royan',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Paris_-_The_Eiffel_Tower_in_spring_-_2307.jpg',
  },
  {
    name: 'Colosseum',
    the: true,
    place: 'Rome, Italy',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Colosseum_of_Rome_and_Roman_forum.jpg/1920px-Colosseum_of_Rome_and_Roman_forum.jpg',
    credit: 'Wilfredor',
    license: 'CC0',
    source: 'https://commons.wikimedia.org/wiki/File:Colosseum_of_Rome_and_Roman_forum.jpg',
  },
  {
    name: 'Taj Mahal',
    the: true,
    place: 'Agra, India',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Taj_Mahal%2C_Agra%2C_India_edit2.jpg/1920px-Taj_Mahal%2C_Agra%2C_India_edit2.jpg',
    credit: 'Yann; edited by King of Hearts',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Taj_Mahal%2C_Agra%2C_India_edit2.jpg',
  },
  {
    name: 'Machu Picchu',
    place: 'Cusco Region, Peru',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Machu_Picchu_Panorama_2025.jpg/1920px-Machu_Picchu_Panorama_2025.jpg',
    credit: 'Jorge Castro Ruso',
    license: 'CC BY-SA 2.0',
    source: 'https://commons.wikimedia.org/wiki/File:Machu_Picchu_Panorama_2025.jpg',
  },
  {
    name: 'Great Wall',
    the: true,
    place: 'Badaling, China',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Badaling_China_Great-Wall-of-China-01.jpg/1920px-Badaling_China_Great-Wall-of-China-01.jpg',
    credit: 'CEphoto, Uwe Aranas',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Badaling_China_Great-Wall-of-China-01.jpg',
  },
  {
    name: 'Sydney Opera House',
    the: true,
    place: 'Sydney, Australia',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Sydney_Opera_House_and_Harbour_Bridge_Dusk_%282%29_2019-06-21.jpg/1920px-Sydney_Opera_House_and_Harbour_Bridge_Dusk_%282%29_2019-06-21.jpg',
    credit: 'Benh LIEU SONG (Flickr)',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sydney_Opera_House_and_Harbour_Bridge_Dusk_%282%29_2019-06-21.jpg',
  },
  {
    name: 'Golden Gate Bridge',
    the: true,
    place: 'San Francisco, USA',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Golden_Gate_Bridge_as_seen_from_Marshall%E2%80%99s_Beach%2C_March_2018.jpg/1920px-Golden_Gate_Bridge_as_seen_from_Marshall%E2%80%99s_Beach%2C_March_2018.jpg',
    credit: 'Frank Schulenburg',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Golden_Gate_Bridge_as_seen_from_Marshall%E2%80%99s_Beach%2C_March_2018.jpg',
  },
  {
    name: 'Oia, Santorini',
    place: 'Cyclades, Greece',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/1000_Three_domes_of_Oia_in_Santorini_Photo_by_Giles_Laurent.jpg/1920px-1000_Three_domes_of_Oia_in_Santorini_Photo_by_Giles_Laurent.jpg',
    credit: 'Giles Laurent',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:1000_Three_domes_of_Oia_in_Santorini_Photo_by_Giles_Laurent.jpg',
  },
  {
    name: 'Treasury at Petra',
    the: true,
    place: 'Ma\'an, Jordan',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Al-Khazneh_%28The_Treasury%29_2%2C_Petra%2C_Jordan.jpg/1920px-Al-Khazneh_%28The_Treasury%29_2%2C_Petra%2C_Jordan.jpg',
    credit: 'Vyacheslav Argenberg',
    license: 'CC BY 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Al-Khazneh_%28The_Treasury%29_2%2C_Petra%2C_Jordan.jpg',
  },
  {
    name: 'Christ the Redeemer',
    place: 'Rio de Janeiro, Brazil',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Redentor_Over_Clouds_1.jpg/1920px-Redentor_Over_Clouds_1.jpg',
    credit: 'Donatas Dabravolskas',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Redentor_Over_Clouds_1.jpg',
  },
  {
    name: 'Mount Fuji',
    place: 'Honshu, Japan',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Lake_Kawaguchiko_Sakura_Mount_Fuji_4.JPG/1920px-Lake_Kawaguchiko_Sakura_Mount_Fuji_4.JPG',
    credit: 'Midori',
    license: 'CC BY 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Lake_Kawaguchiko_Sakura_Mount_Fuji_4.JPG',
  },
  {
    name: 'Stonehenge',
    place: 'Wiltshire, England',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Stonehenge%2C_Condado_de_Wiltshire%2C_Inglaterra%2C_2014-08-12%2C_DD_18.JPG/1920px-Stonehenge%2C_Condado_de_Wiltshire%2C_Inglaterra%2C_2014-08-12%2C_DD_18.JPG',
    credit: 'Diego Delso',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Stonehenge%2C_Condado_de_Wiltshire%2C_Inglaterra%2C_2014-08-12%2C_DD_18.JPG',
  },
  {
    name: 'Great Sphinx',
    the: true,
    place: 'Giza, Egypt',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Great_Sphinx_of_Giza_%28%D8%A3%D8%A8%D9%88_%D8%A7%D9%84%D9%87%D9%88%D9%84%29.jpg/1920px-Great_Sphinx_of_Giza_%28%D8%A3%D8%A8%D9%88_%D8%A7%D9%84%D9%87%D9%88%D9%84%29.jpg',
    credit: 'Petar Milošević',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Great_Sphinx_of_Giza_%28%D8%A3%D8%A8%D9%88_%D8%A7%D9%84%D9%87%D9%88%D9%84%29.jpg',
  },
  {
    name: 'Neuschwanstein Castle',
    place: 'Bavaria, Germany',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Neuschwanstein_Castle_2024.jpg/1920px-Neuschwanstein_Castle_2024.jpg',
    credit: 'Wilfredor',
    license: 'CC0',
    source: 'https://commons.wikimedia.org/wiki/File:Neuschwanstein_Castle_2024.jpg',
  },
  {
    name: 'Times Square',
    place: 'New York City, USA',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/New_York_City_%28New_York%2C_USA%29%2C_Times_Square-Duffy_Square_--_2012_--_6380.jpg/1920px-New_York_City_%28New_York%2C_USA%29%2C_Times_Square-Duffy_Square_--_2012_--_6380.jpg',
    credit: 'Dietmar Rabich',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:New_York_City_%28New_York%2C_USA%29%2C_Times_Square-Duffy_Square_--_2012_--_6380.jpg',
  },
  {
    name: 'Grand Canyon',
    the: true,
    place: 'Arizona, USA',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Grand_Canyon_Hopi_Point_with_rainbow_2013.jpg/1920px-Grand_Canyon_Hopi_Point_with_rainbow_2013.jpg',
    credit: 'Tuxyso',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Grand_Canyon_Hopi_Point_with_rainbow_2013.jpg',
  },
  {
    name: 'Big Ben',
    place: 'London, England',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Palace_of_Westminster_seen_from_the_north_bank_of_the_Thames%2C_London.jpg/1920px-Palace_of_Westminster_seen_from_the_north_bank_of_the_Thames%2C_London.jpg',
    credit: 'Christian David',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Palace_of_Westminster_seen_from_the_north_bank_of_the_Thames%2C_London.jpg',
  },
  {
    name: 'Angkor Wat',
    place: 'Siem Reap, Cambodia',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Angkor_Wat_with_its_reflection_%28cropped%29.jpg/1920px-Angkor_Wat_with_its_reflection_%28cropped%29.jpg',
    credit: 'Satdeep Gill',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Angkor_Wat_with_its_reflection_%28cropped%29.jpg',
  },
  {
    name: 'Burj Khalifa',
    the: true,
    place: 'Dubai, UAE',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Burj_Khalifa_Dubai%2C_UAE_at_Sunset_001_by_Eric_Chamchoum.jpg/1920px-Burj_Khalifa_Dubai%2C_UAE_at_Sunset_001_by_Eric_Chamchoum.jpg',
    credit: 'ECWiki1',
    license: 'CC BY 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Burj_Khalifa_Dubai%2C_UAE_at_Sunset_001_by_Eric_Chamchoum.jpg',
  },
  {
    name: 'Niagara Falls',
    place: 'Ontario, Canada',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Canadian_Niagara_Wonder_at_Horseshoe_Falls_%2C_Ontario_in_2017.jpg/1920px-Canadian_Niagara_Wonder_at_Horseshoe_Falls_%2C_Ontario_in_2017.jpg',
    credit: 'Pierre André',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Canadian_Niagara_Wonder_at_Horseshoe_Falls_%2C_Ontario_in_2017.jpg',
  },
  {
    name: 'Ahu Tongariki',
    place: 'Rapa Nui, Chile',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Moai_on_Rapa_Nui_after_they_were_stood_back_up.jpg/1920px-Moai_on_Rapa_Nui_after_they_were_stood_back_up.jpg',
    credit: 'Docrgd',
    license: 'CC BY 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Moai_on_Rapa_Nui_after_they_were_stood_back_up.jpg',
  },
  {
    name: 'St. Basil\'s Cathedral',
    place: 'Moscow, Russia',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Saint_Basil%27s_Cathedral_and_the_Red_Square.jpg/1920px-Saint_Basil%27s_Cathedral_and_the_Red_Square.jpg',
    credit: 'U.S. Department of State',
    license: 'Public domain',
    source: 'https://commons.wikimedia.org/wiki/File:Saint_Basil%27s_Cathedral_and_the_Red_Square.jpg',
  },
  {
    name: 'Hollywood Sign',
    the: true,
    place: 'Los Angeles, USA',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hollywood_Sign_%28Zuschnitt%29.jpg/1920px-Hollywood_Sign_%28Zuschnitt%29.jpg',
    credit: 'Thomas Wolf, www.foto-tw.de',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Hollywood_Sign_%28Zuschnitt%29.jpg',
  },
  {
    name: 'La Sagrada Familia',
    place: 'Barcelona, Spain',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Sagrada_Familia_Basilica%2C_Barcelona_05.jpg/1920px-Sagrada_Familia_Basilica%2C_Barcelona_05.jpg',
    credit: 'Ank Kumar',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Sagrada_Familia_Basilica%2C_Barcelona_05.jpg',
  },
  {
    name: 'Antelope Canyon',
    place: 'Arizona, USA',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Upper_Antelope_Canyon_03_2013.jpg/1920px-Upper_Antelope_Canyon_03_2013.jpg',
    credit: 'Tuxyso',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Upper_Antelope_Canyon_03_2013.jpg',
  },
  {
    name: 'Grand Canal',
    the: true,
    place: 'Venice, Italy',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Canal_Grande_Chiesa_della_Salute_e_Dogana_dal_ponte_dell_Accademia.jpg/1920px-Canal_Grande_Chiesa_della_Salute_e_Dogana_dal_ponte_dell_Accademia.jpg',
    credit: 'Wolfgang Moroder',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Canal_Grande_Chiesa_della_Salute_e_Dogana_dal_ponte_dell_Accademia.jpg',
  },
  {
    name: 'Table Mountain',
    place: 'Cape Town, South Africa',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Cape_Town_%28ZA%29%2C_Table_Mountain_--_2024_--_2825.jpg/1920px-Cape_Town_%28ZA%29%2C_Table_Mountain_--_2024_--_2825.jpg',
    credit: 'Dietmar Rabich',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Cape_Town_%28ZA%29%2C_Table_Mountain_--_2024_--_2825.jpg',
  },
  {
    name: 'Chichen Itza',
    place: 'Yucatan, Mexico',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/El_Castillo_Stitch_2008_Edit_2.jpg/1920px-El_Castillo_Stitch_2008_Edit_2.jpg',
    credit: 'Fcb981',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:El_Castillo_Stitch_2008_Edit_2.jpg',
  },
  {
    name: 'Moraine Lake',
    place: 'Banff, Canada',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Lake_Moraine-Banff_National_Park.jpg/1920px-Lake_Moraine-Banff_National_Park.jpg',
    credit: 'Florian Fuchs',
    license: 'CC BY 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Lake_Moraine-Banff_National_Park.jpg',
  },
  {
    name: 'Mount Everest',
    place: 'Himalayas, Nepal',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg/1920px-Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg',
    credit: 'Luca Galuzzi (Lucag)',
    license: 'CC BY-SA 2.5',
    source: 'https://commons.wikimedia.org/wiki/File:Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg',
  },
  {
    name: 'Golden Temple',
    the: true,
    place: 'Amritsar, India',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Harmandir_Sahib%2C_Amritsar%2C_India.jpg/1920px-Harmandir_Sahib%2C_Amritsar%2C_India.jpg',
    credit: 'Dey.sandip',
    license: 'CC BY-SA 4.0',
    source: 'https://commons.wikimedia.org/wiki/File:Harmandir_Sahib%2C_Amritsar%2C_India.jpg',
  },
  {
    name: 'Petronas Towers',
    the: true,
    place: 'Kuala Lumpur, Malaysia',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Kuala_Lumpur_Malaysia_Petronas-Twin-Towers-01.jpg/1920px-Kuala_Lumpur_Malaysia_Petronas-Twin-Towers-01.jpg',
    credit: 'CEphoto, Uwe Aranas',
    license: 'CC BY-SA 3.0',
    source: 'https://commons.wikimedia.org/wiki/File:Kuala_Lumpur_Malaysia_Petronas-Twin-Towers-01.jpg',
  },
];
